### ISSUE TITLE
Size selection broken for multi-monitor setups

### ISSUE THREAD

**Issue by wengh** [meziantou/Window-Manager#1]
The size selector shows up on both screens
![image](https://i.imgur.com/hNRk4Rg.png)
But only the one on the primary screen works. The other one doesn't respond to mouse drag at all.

**Comment by meziantou** [comment]
I can reproduce the problem on my machine. I haven't used this tool for a long time (I now use [FancyZones](https://docs.microsoft.com/en-us/windows/powertoys/fancyzones?WT.mc_id=DT-MVP-5003978) to manage windows), so I cannot tell if it's a recent issue nor what could be the cause.

If you want, you can submit a PR to fix this issue.

**Comment by wengh** [comment]
Didn't know PowerToy had a window manager... Maybe I should also use it instead of this.
