### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by flyingrhinonz** [meziantou/Window-Manager#3]
Thanks for a wonderful product. So useful!

Can you please add to the hotkeys:

Minimize window 
Maximize window (if it is different to the existing "Full screen")

I know you can do in windows alt space n / x  to minimize/maximize , but some programs capture or disable the alt-space (for example putty) , and it would be super useful to have your program do this functionality rather than installing a separate keyboard mapping program.

Thanks.

**Comment by meziantou** [comment]
> Minimize window

Already implemented in Windows: <kbd>Win + Down arrow</kbd>

Also, while not available in the UI, you should be able to set it in the configuration file  `%localappdata%\Meziantou\WindowManager\settings.xml`

> Maximize window

Already implemented in Windows: <kbd>Win + Up arrow</kbd>. Also, FullScreen should do the same.
